### ISSUE TITLE
安装完后./glance 显示no such file or directory

### ISSUE THREAD

**Issue by su829186** [TimothyYe/glance#7]
安装完后./glance 显示no such file or directory，如何解决呢

**Comment by TimothyYe** [comment]
你如何安装的？

**Comment by Tjiawei** [comment]
同问，我也遇到一样的问题，我是直接下载到本地，然后拖到虚拟机后解压./glance，出现此错误
![1730442609614](https://github.com/user-attachments/assets/0f51ef3e-beec-456f-90f3-39b60eec107a)

**Comment by Tjiawei** [comment]
> 同问，我也遇到一样的问题，我是直接下载到本地，然后拖到虚拟机后解压./glance，出现此错误 ![1730442609614](https://private-user-images.githubusercontent.com/186988903/382203260-0f51ef3e-beec-456f-90f3-39b60eec107a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDUyNTYsIm5iZiI6MTczMDQ0NDk1NiwicGF0aCI6Ii8xODY5ODg5MDMvMzgyMjAzMjYwLTBmNTFlZjNlLWJlZWMtNDU2Zi05MGYzLTM5YjYwZWVjMTA3YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwNzA5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmE3YThlY2Y0ZjEwNjQ5NmJmN2RiMDY0ZGIxMjhlYjU0ZmIwZjVkYzk3MDk1NTIxMGE4NTkyYjI5OTIwYjRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jnyNyOW2cmsUUnwlP0fXNz_y33bh7moOf7PiptV2aks)

另外，给了glance 权限之后运行显示Please input the file name
![image](https://github.com/user-attachments/assets/f1366d3a-41e2-4bd3-be3d-cd4af29d72b9)

**Comment by hamburger-114514** [comment]
同问

**Comment by TimothyYe** [comment]
@Tjiawei @hamburger-114514 这是正常的吧:
```bash
./glance /path/to/abc.txt
```

得带上参数，参数就是文本文件的路径
